"""refactor book global copy local code

Revision ID: f3a9c2e1d4b5
Revises: b2f3a8d1e6c9
Create Date: 2026-08-22

Book is strictly GLOBAL (no internal_code, no school_id).
BookCopy is LOCAL per school with code + UniqueConstraint(school_id, code).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a9c2e1d4b5'
down_revision: Union[str, Sequence[str], None] = 'b2f3a8d1e6c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- books: remove internal_code and its constraints ---
    # check constraint
    op.execute(
        "ALTER TABLE books DROP CONSTRAINT IF EXISTS "
        "check_isbn_or_internal_code_present"
    )
    # unique on books.internal_code (autogenerated name)
    op.execute(
        "ALTER TABLE books DROP CONSTRAINT IF EXISTS "
        "books_internal_code_key"
    )
    # also handle generic unique that alembic may have created with hash
    # try to drop by dropping column will cascade, but be safe:
    op.execute("ALTER TABLE books DROP COLUMN IF EXISTS internal_code")

    # --- book_copies: rename internal_code -> code ---
    # drop old unique on internal_code
    op.execute(
        "ALTER TABLE book_copies DROP CONSTRAINT IF EXISTS "
        "book_copies_internal_code_key"
    )
    op.execute(
        "ALTER TABLE book_copies DROP CONSTRAINT IF EXISTS "
        "uq_book_copies_internal_code"
    )
    # rename column
    op.execute(
        "ALTER TABLE book_copies RENAME COLUMN internal_code TO code"
    )
    # create new composite unique per school
    op.create_unique_constraint(
        'uq_school_copy_code', 'book_copies', ['school_id', 'code']
    )


def downgrade() -> None:
    op.drop_constraint('uq_school_copy_code', 'book_copies', type_='unique')
    op.execute("ALTER TABLE book_copies RENAME COLUMN code TO internal_code")
    op.create_unique_constraint(
        'book_copies_internal_code_key', 'book_copies', ['internal_code']
    )
    op.add_column(
        'books',
        sa.Column('internal_code', sa.String(), nullable=True),
    )
    op.create_unique_constraint(
        'books_internal_code_key', 'books', ['internal_code']
    )
    op.create_check_constraint(
        'check_isbn_or_internal_code_present',
        'books',
        'isbn IS NOT NULL OR internal_code IS NOT NULL',
    )
